version: "3"

networks:
  observability:
    driver: bridge

volumes:
  logs_data:

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=person-service
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespassword
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - observability

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8005:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./db/pgadmin-servers.json:/pgadmin4/servers.json
    networks:
      - observability
    depends_on:
      - postgres

  loki:
    image: grafana/loki:2.2.0
    command: -config.file=/etc/loki/loki-local.yaml
    ports:
      - 3101:3100 # loki needs to be exposed so it receives logs
    volumes:
      - ./etc/loki-local.yaml:/etc/loki/loki-local.yaml
    networks:
      - observability
    depends_on:
      - backend

  jaeger:
    image: jaegertracing/all-in-one:1.27
    ports:
      - 14268:14268 # Jaeger Thrift HTTP
      - 14250:14250 # Jaeger GRPC
      - 16686:16686 # Jaeger UI
      - 16687:16687 # Jaeger Admin UI
    networks:
      - observability
    depends_on:
      - backend

  promtail:
    image: grafana/promtail:2.2.0
    command: -config.file=/etc/promtail/promtail-local.yaml
    volumes:
      - ./etc/promtail-local.yaml:/etc/promtail/promtail-local.yaml
      - logs_data:/app/logs
    networks:
      - observability
    depends_on:
      - loki

  prometheus:
    image: prom/prometheus:latest
    entrypoint:
      - /bin/prometheus
      - --config.file=/etc/prometheus.yaml
    ports:
      - 9090:9090
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
    networks:
      - observability
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:7.4.0-ubuntu
    ports:
      - 3001:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./etc/grafana-datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./etc/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    networks:
      - observability
    depends_on:
      - prometheus
      - jaeger
      - loki

  otel-collector:
    image: otel/opentelemetry-collector:0.35.0
    command: "--config /etc/otel-config.yaml"
    ports:
      - 4317:4317 # OpenTelemetry GRPC
      - 4318:4318 # OpenTelemetry HTTP
    volumes:
      - ./etc/otel-config.yaml:/etc/otel-config.yaml
    networks:
      - observability
    depends_on:
      - jaeger
      - frontend

  chrome:
    build:
      context: ./selenium-tests
      dockerfile: Dockerfile-standalone-chrome
    shm_size: 256M
    networks:
      - observability
    ports:
      - 4444:4444

  backend:
    build:
      context: ./person-service
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/person-service
      DB_USER: postgres
      DB_PASS: postgrespassword
    volumes:
      - logs_data:/app/logs
    networks:
      - observability
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - observability
    depends_on:
      - backend
