{
 "title": "Custom Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Errors count",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "latency_count{operation=\"/api/person-service/persons\",service_name=\"person-service-frontend\",span_kind=\"SPAN_KIND_INTERNAL\",status_code=\"STATUS_CODE_ERROR\"}"
    }
   ]
  },
  {
   "title": "Error ratio",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "latency_count{operation=\"/api/person-service/persons\",service_name=\"person-service-frontend\",span_kind=\"SPAN_KIND_INTERNAL\"}"
    }
   ]
  },
  {
   "title": "Fetch persons",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "latency_bucket{operation=\"HTTP GET\",service_name=\"person-service-frontend\",span_kind=\"SPAN_KIND_CLIENT\",status_code=\"STATUS_CODE_UNSET\"}",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}