global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "jaeger"
    static_configs:
      - targets: ["jaeger:16687"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "person-service"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["backend:8090"]
